defmodule ExAxos.Schema.AccountAuthorizationsInfo do
  @moduledoc """
  Provides struct and type for a Schema.AccountAuthorizationsInfo
  """

  @type t :: %__MODULE__{
          accountNumber: String.t() | nil,
          achDigests: [ExAxos.Schema.SimpleAccountAuthorizationsAchDigest.t()] | nil,
          achcDigests: [ExAxos.Schema.SimpleAccountAuthorizationsAchDigest.t()] | nil,
          addressChangeWarn: boolean | nil,
          adjSystDistRmdFlag: boolean | nil,
          authParty1: String.t() | nil,
          authParty2: String.t() | nil,
          authParty3: String.t() | nil,
          authParty4: String.t() | nil,
          authPartyIndependentFlag: boolean | nil,
          authPartyNoteLines: [String.t()] | nil,
          cashDistCount: integer | nil,
          cashDistsSinceDate: String.t() | nil,
          changeAchDate: String.t() | nil,
          contributionAccountType: String.t() | nil,
          contributionChangeTermSystAch: String.t() | nil,
          contributionEstablishSystAch: String.t() | nil,
          contributionOnDemandAch: boolean | nil,
          courtOrderFlag: boolean | nil,
          iraChangeCheckDate: String.t() | nil,
          iraCheckToAddrDate: String.t() | nil,
          iraEstabCheckDate: String.t() | nil,
          iraEstabSystAch: String.t() | nil,
          iraInternalTransferDate: String.t() | nil,
          iraWireDate: String.t() | nil,
          lastAddressChangeDate: String.t() | nil,
          otherNoteLines: [String.t()] | nil,
          pledgedCollateralFlag: boolean | nil,
          poaFlag: boolean | nil,
          systDistFlag: boolean | nil,
          taxLienFlag: boolean | nil,
          wireAba: String.t() | nil,
          wireBankAccountName: String.t() | nil,
          wireBankAccountNo: String.t() | nil,
          wireNoteLines: [String.t()] | nil,
          wirePurpose: String.t() | nil
        }

  defstruct [
    :accountNumber,
    :achDigests,
    :achcDigests,
    :addressChangeWarn,
    :adjSystDistRmdFlag,
    :authParty1,
    :authParty2,
    :authParty3,
    :authParty4,
    :authPartyIndependentFlag,
    :authPartyNoteLines,
    :cashDistCount,
    :cashDistsSinceDate,
    :changeAchDate,
    :contributionAccountType,
    :contributionChangeTermSystAch,
    :contributionEstablishSystAch,
    :contributionOnDemandAch,
    :courtOrderFlag,
    :iraChangeCheckDate,
    :iraCheckToAddrDate,
    :iraEstabCheckDate,
    :iraEstabSystAch,
    :iraInternalTransferDate,
    :iraWireDate,
    :lastAddressChangeDate,
    :otherNoteLines,
    :pledgedCollateralFlag,
    :poaFlag,
    :systDistFlag,
    :taxLienFlag,
    :wireAba,
    :wireBankAccountName,
    :wireBankAccountNo,
    :wireNoteLines,
    :wirePurpose
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountNumber: {:string, :generic},
      achDigests: [{ExAxos.Schema.SimpleAccountAuthorizationsAchDigest, :t}],
      achcDigests: [{ExAxos.Schema.SimpleAccountAuthorizationsAchDigest, :t}],
      addressChangeWarn: :boolean,
      adjSystDistRmdFlag: :boolean,
      authParty1: {:string, :generic},
      authParty2: {:string, :generic},
      authParty3: {:string, :generic},
      authParty4: {:string, :generic},
      authPartyIndependentFlag: :boolean,
      authPartyNoteLines: [string: :generic],
      cashDistCount: :integer,
      cashDistsSinceDate: {:string, :generic},
      changeAchDate: {:string, :generic},
      contributionAccountType: {:string, :generic},
      contributionChangeTermSystAch: {:string, :generic},
      contributionEstablishSystAch: {:string, :generic},
      contributionOnDemandAch: :boolean,
      courtOrderFlag: :boolean,
      iraChangeCheckDate: {:string, :generic},
      iraCheckToAddrDate: {:string, :generic},
      iraEstabCheckDate: {:string, :generic},
      iraEstabSystAch: {:string, :generic},
      iraInternalTransferDate: {:string, :generic},
      iraWireDate: {:string, :generic},
      lastAddressChangeDate: {:string, :generic},
      otherNoteLines: [string: :generic],
      pledgedCollateralFlag: :boolean,
      poaFlag: :boolean,
      systDistFlag: :boolean,
      taxLienFlag: :boolean,
      wireAba: {:string, :generic},
      wireBankAccountName: {:string, :generic},
      wireBankAccountNo: {:string, :generic},
      wireNoteLines: [string: :generic],
      wirePurpose: {:string, :generic}
    ]
  end
end
